### ISSUE TITLE
Chart files should match chart name

### ISSUE THREAD

**Issue by strangiato** [openshift-helm-charts/charts#1614]
It looks like when indexing the charts, the charts are currently appending `redhat-` to the front of the chart name, which unfortunately breaks helm dependencies feature.

For example, if I create the following `Chart.yaml` file:

```
apiVersion: v2
name: my-chart
description: A Helm example
type: application

version: 0.1.0

dependencies:
  - name: redhat-postgresql-persistent
    version: "0.0.3"
    repository: "https://charts.openshift.io"
```

And run the following to pull the dependent chart:

```
helm dependency build .
```

The chart successfully resolves but it downloads the file `postgresql-persistent-0.0.3.tgz`.  Then when attempting to deploy the chart it complains that the dependencies aren't up to date because it is looking for a file called `redhat-postgresql-persistent-0.0.3.tgz`.  When running a `helm install` it generates the following:

```
Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redhat-postgresql-persistent
```
