### ISSUE TITLE
Can not use infinispan chart as a dependency

### ISSUE THREAD

**Issue by ehsan-tashkhisi** [openshift-helm-charts/charts#655]
I am somehow confused and do not know where to ask my question, I have problem when adding the Infinispan chart as a dependency to my chart as below:

```
dependencies:
  - name: infinispan-infinispan
    alias: infinispan
    version: 0.3.0
    repository: https://charts.openshift.io/
```
After running `helm dep up`

The content of the charts directory is as below:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/61104684/207938752-53f25946-cd0e-4968-970d-597e46f3dd94.png">

As you can see the tar file was generated with the name `infinispan-infinispan` but the name of the folder inside that tar file is `infinispan`. for this reason when I run `helm install` command I get the following error:
```
INSTALLATION FAILED: found in Chart.yaml, but missing in charts/ directory: infinispan-infinispan
```
Based on Helm documentation `name` in dependency should match the `name` in the chart but with this chart, it is not possible, because the name that I should use in dependency is `infinispan-infinispan` but the name of the chart is infinispan.
